package com.stla.patterns.observer;

/**
 * Observer Pattern: Event types for the notification system.
 */
public record AppEvent(EventType type, String actorProfileId, String targetId, String message) {
    public enum EventType {
        USER_REGISTERED,
        ENROLLMENT_CREATED, PAYMENT_COMPLETED, PAYMENT_FAILED, COURSE_APPROVED, COURSE_REJECTED,
        COURSE_SUBMITTED, COURSE_PUBLISHED,
        LESSON_COMPLETED, COURSE_PROGRESS_UPDATED, COURSE_COMPLETED,
        QUIZ_SUBMITTED, QUIZ_PASSED, QUIZ_FAILED,
        NEW_LESSON_ADDED, NEW_RESOURCE_ADDED, NEW_QUIZ_ADDED,
        WITHDRAWAL_COMPLETED,
        INSTRUCTOR_REVENUE_ADDED, ADMIN_COMMISSION_ADDED,
        CERTIFICATE_ISSUED,
        STUDENT_REVIEW_ADDED,
        INSTRUCTOR_VERIFICATION_SUBMITTED, INSTRUCTOR_VERIFIED, INSTRUCTOR_REJECTED, INSTRUCTOR_RESUBMITTED
    }
}
